/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LoanReferral = IDL.Record({
  'member' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const MemberReferral = IDL.Record({
  'referrer' : IDL.Principal,
  'newMember' : IDL.Principal,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const Time = IDL.Int;
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'bankDetails' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'active' : IDL.Bool,
  'referrer' : IDL.Opt(IDL.Principal),
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoanReferral' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'addMemberReferral' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'getAllLoanReferrals' : IDL.Func([], [IDL.Vec(LoanReferral)], ['query']),
  'getAllMemberReferrals' : IDL.Func([], [IDL.Vec(MemberReferral)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getLoanReferral' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(LoanReferral)],
      ['query'],
    ),
  'getMemberReferral' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberReferral)],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Nat],
      [],
      [],
    ),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLevel' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LoanReferral = IDL.Record({
    'member' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const MemberReferral = IDL.Record({
    'referrer' : IDL.Principal,
    'newMember' : IDL.Principal,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const Time = IDL.Int;
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'bankDetails' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'active' : IDL.Bool,
    'referrer' : IDL.Opt(IDL.Principal),
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoanReferral' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'addMemberReferral' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'getAllLoanReferrals' : IDL.Func([], [IDL.Vec(LoanReferral)], ['query']),
    'getAllMemberReferrals' : IDL.Func(
        [],
        [IDL.Vec(MemberReferral)],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getLoanReferral' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(LoanReferral)],
        ['query'],
      ),
    'getMemberReferral' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberReferral)],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Nat],
        [],
        [],
      ),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLevel' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };