/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LoanReferralRecord = IDL.Record({
  'id' : IDL.Nat,
  'referrer' : IDL.Principal,
  'loanAmount' : IDL.Nat,
  'commission' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'borrowerName' : IDL.Text,
});
export const LoanReferral = IDL.Record({
  'member' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const MemberReferral = IDL.Record({
  'referrer' : IDL.Principal,
  'newMember' : IDL.Principal,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Text,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'bankDetails' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'active' : IDL.Bool,
  'referrer' : IDL.Opt(IDL.Principal),
  'balance' : IDL.Nat,
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoanReferral' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'addMemberReferral' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'generateOTPForPhone' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllLoanReferralRecords' : IDL.Func(
      [],
      [IDL.Vec(LoanReferralRecord)],
      ['query'],
    ),
  'getAllLoanReferrals' : IDL.Func([], [IDL.Vec(LoanReferral)], ['query']),
  'getAllMemberReferrals' : IDL.Func([], [IDL.Vec(MemberReferral)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getLoanReferral' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(LoanReferral)],
      ['query'],
    ),
  'getLoanReferralRecord' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(LoanReferralRecord)],
      ['query'],
    ),
  'getMemberReferral' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberReferral)],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getTotalEarnings' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalLevelIncome' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalLoanReferralCommission' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalTeamSize' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserLoanReferralRecords' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LoanReferralRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markLevelRewarded' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Nat],
      [],
      [],
    ),
  'rejectWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLoanReferral' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateLevel' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'verifyPhoneAndLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Principal)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LoanReferralRecord = IDL.Record({
    'id' : IDL.Nat,
    'referrer' : IDL.Principal,
    'loanAmount' : IDL.Nat,
    'commission' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'borrowerName' : IDL.Text,
  });
  const LoanReferral = IDL.Record({
    'member' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const MemberReferral = IDL.Record({
    'referrer' : IDL.Principal,
    'newMember' : IDL.Principal,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'bankDetails' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'active' : IDL.Bool,
    'referrer' : IDL.Opt(IDL.Principal),
    'balance' : IDL.Nat,
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoanReferral' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'addMemberReferral' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'approveWithdrawalRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'generateOTPForPhone' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllLoanReferralRecords' : IDL.Func(
        [],
        [IDL.Vec(LoanReferralRecord)],
        ['query'],
      ),
    'getAllLoanReferrals' : IDL.Func([], [IDL.Vec(LoanReferral)], ['query']),
    'getAllMemberReferrals' : IDL.Func(
        [],
        [IDL.Vec(MemberReferral)],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getLoanReferral' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(LoanReferral)],
        ['query'],
      ),
    'getLoanReferralRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LoanReferralRecord)],
        ['query'],
      ),
    'getMemberReferral' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberReferral)],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getTotalEarnings' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalLevelIncome' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalLoanReferralCommission' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalTeamSize' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserLoanReferralRecords' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LoanReferralRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markLevelRewarded' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal), IDL.Nat],
        [],
        [],
      ),
    'rejectWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLoanReferral' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateLevel' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'verifyPhoneAndLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Principal)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };