/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LoanReferral { 'member' : Principal, 'amount' : bigint }
export interface MemberReferral {
  'referrer' : Principal,
  'newMember' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'active' : boolean,
  'referrer' : [] | [Principal],
  'balance' : bigint,
  'name' : string,
  'level' : bigint,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'bankDetails' : string,
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : string };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoanReferral' : ActorMethod<[Principal, bigint], undefined>,
  'addMemberReferral' : ActorMethod<[Principal, Principal], undefined>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'approveWithdrawalRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWithdrawalRequest' : ActorMethod<[bigint, string], bigint>,
  'deposit' : ActorMethod<[bigint], undefined>,
  'getAllLoanReferrals' : ActorMethod<[], Array<LoanReferral>>,
  'getAllMemberReferrals' : ActorMethod<[], Array<MemberReferral>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getLoanReferral' : ActorMethod<[Principal], [] | [LoanReferral]>,
  'getMemberReferral' : ActorMethod<[Principal], [] | [MemberReferral]>,
  'getPendingWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, [] | [Principal], bigint],
    undefined
  >,
  'rejectWithdrawalRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLevel' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];